language: python
python:
  - 3.5
install:
  - python setup.py install
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  - nosetests -s -vv --with-coverage --cover-package=.--detailed-errors
after_success:
  - coveralls